### ISSUE TITLE
Vagrant Up install issue with Jenkins

### ISSUE THREAD

**Issue by jwolfram** [oneops/setup#103]
==> default: doing git pull
==> default: Already up-to-date.
==> default: Stopping jenkins server
==> default: java -jar /home/oneops/build/build-wf/war/WEB-INF/jenkins-cli.jar safe-shutdown
**==> default: Error: Unable to access jarfile /home/oneops/build/build-wf/war/WEB-INF/jenkins-cli.jar**
==> default: Downloading jenkins war: http://mirror.xmission.com/jenkins/war-stable/1.642.4/jenkins.war
**==> default: rake aborted!
==> default: OpenURI::HTTPError: 404 Not Found
==> default: /home/oneops/build/build-wf/Rakefile:38:in `block (2 levels) in <top (required)>'
==> default: /home/oneops/build/build-wf/Rakefile:37:in `open'
==> default: /home/oneops/build/build-wf/Rakefile:37:in `block in <top (required)>'
==> default: /usr/local/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
==> default: Tasks: TOP => install => war
==> default: (See full trace by running task with --trace)**
==> default: rake install failed, retrying
==> default: Downloading jenkins war: http://mirror.xmission.com/jenkins/war-stable/1.642.4/jenkins.war
**==> default: rake aborted!
==> default: OpenURI::HTTPError: 404 Not Found
==> default: /home/oneops/build/build-wf/Rakefile:38:in `block (2 levels) in <top (required)>'
==> default: /home/oneops/build/build-wf/Rakefile:37:in `open'
==> default: /home/oneops/build/build-wf/Rakefile:37:in `block in <top (required)>'
==> default: /usr/local/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
==> default: Tasks: TOP => install => war
==> default: (See full trace by running task with --trace)**
==> default: Can not instal jenkins, exiting :-(
_The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong._

**Comment by jwolfram** [comment]
Issue was resolved by re-provisioning.

**Comment by yrmallu** [comment]
@jwolfram I'm getting the same issue. Can you please let me know how to fix

**Comment by yrmallu** [comment]
@jwolfram re-provision the entire oneops stack.  What do you mean that? 

What are the steps?

Is there any other ways?

**Comment by jwolfram** [comment]
@yrmallu I mean go back in the process and start over per the documentation. I am sure there are probably other ways, but this way worked and it doesn't involve modifying any of the steps or code, etc. I don't know why it failed the first time(s), but it did eventually work. Apologies for not having a more in-depth answer, but that is what I did...start over and do it again from fresh.

**Comment by yrmallu** [comment]
@jwolfram I'm doing the same running from  the dev-lools/setup-scripts but I'm getting the same error every time. If I change the Jenkins version to 2.7.1 then it's failing while building the projects.

Any help would be appreciated.

**Comment by vmSmart** [comment]
This problem still exists.   There is a bad URL in the Jenkins portion of the script.

**Comment by glhome** [comment]
I am seeing the same issue...
