### ISSUE TITLE
I'm getting the error in cost summary and metrics (Health)

### ISSUE THREAD

**Issue by yrmallu** [oneops/setup#106]
Started GET "/devinstance/organization/cost?authenticity_token=[FILTERED]" for 121.242.18.68 at 2017-04-25 12:39:26 +0000
Processing by OrganizationController#cost as JS
Parameters: {"authenticity_token"=>"[FILTERED]", "org_name"=>"devinstance"}
User Load (0.5ms) SELECT "users".* FROM "users" WHERE "users"."id" = 1 ORDER BY "users"."id" ASC LIMIT 1
Organization Load (0.2ms) SELECT "organizations".* FROM "organizations" WHERE "organizations"."id" = $1 LIMIT 1 [["id", 1]]
HTTP Post (2.1ms) http://search:9200/cost/ci/_search
Failed to fetch 'cost' for nsPath=/devinstance, date range=[2017-04-01, 2017-04-25: Failed. Response code = 404. Response message = Not Found.
HTTP Post (25.5ms) http://search:9200/cms-all/ci/_search
Failed to fetch 'cost_rate' for nsPath /devinstancebom/: Failed. Response code = 500. Response message = Internal Server Error.
HTTP Post (1.0ms) http://search:9200/cost-*/ci/_search
Failed to fetch 'cost_time_histogram' for nsPath=/devinstance, date range=[2017-02-01, 2017-04-25], interval=month: undefined method `[]' for nil:NilClass
Rendered base/cost/_cost.html.erb (0.2ms)
Rendered base/cost/cost.js.erb (0.8ms)
Completed 200 OK in 43ms (Views: 4.0ms | ActiveRecord: 0.7ms | Http: 28.7ms)

**Comment by mosabua** [comment]
We can not reproduce the problem and can not assist you further.
