### ISSUE TITLE
Organization creation is failing.

### ISSUE THREAD

**Issue by sanfern** [oneops/setup#19]
Rails.log output while creating organization.

opening connection to cmsapi...
opened
<- "GET /adapter/rest/cm/simple/cis?ciClassName=account.Organization&ciName=testorg&nsPath=%2F HTTP/1.1\r\nAccept: application/json\r\nX-Cms-User: sferna1\r\nX-Cms-Client: development\r\nUser-Agent: Ruby\r\nConnection: keep-alive\r\nKeep-Alive: 30\r\nHost: cmsapi:8080\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Server: Apache-Coyote/1.1\r\n"
-> "Content-Type: application/json\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Date: Wed, 09 Mar 2016 08:13:51 GMT\r\n"
-> "\r\n"
-> "2\r\n"
reading 2 bytes...
-> "[]"
read 2 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn keep-alive
<- "GET /adapter/rest/md/classes/account.Organization?includeActions=true HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: Ruby\r\nConnection: keep-alive\r\nKeep-Alive: 30\r\nHost: cmsapi:8080\r\n\r\n"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Server: Apache-Coyote/1.1\r\n"
-> "Content-Length: 90\r\n"
-> "Date: Wed, 09 Mar 2016 08:13:51 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 90 bytes...
-> "{\"code\":400,\"errorCode\":3012,\"message\":\"there is no class with name account.Organization\"}"
read 90 bytes
Conn close
^C

**Comment by kfilipovski** [comment]
@sanfern it looks like the setup didn't complete - specifically there is a step that runs `circuit init` which loads the metamodel into the cms db and that's where the account.Organization is defined as well as many other classes.  The reason for this failure is some issues with ruby gem dependencies in the setup scripts.  To fix this try the following:

~~~ bash
vagrant ssh
cd /vagrant
sudo bash -l oo-setup.sh master
~~~

This should re-build and re-install oneops from the 'master' branch which has the fixes for the dem dependencies.

**Comment by sanfern** [comment]
Thanks Kfilipovski.
I used CentOS7 vagrant image. There was conflict of mixlib-shellout gem versions. I removed using  command - sudo gem uninstall -i /usr/local/share/gems mixlib-shellout. 
Then ran above mentioned steps.  Now I am able to create organizations.
