### ISSUE TITLE
Issue Regarding Vagrant Up

### ISSUE THREAD

**Issue by ksskSantosh** [oneops/setup#25]
Hi Team,
The following error is occurred while we are running vagrant up command..
could you please help us..

-------------------------------------------------------------------------------------------------------------------------------
k.santosh@kssksantosh MINGW64 ~/setup (master)
$ vagrant up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/k.santosh/setup/base

**Comment by nimkar** [comment]
@ksskSantosh I see you are trying to run this on Windows. I have tried it on windows and it does not work because of the setup scripts it has to run. Currently it is well tested and works on Linux and Mac.

**Comment by ksskSantosh** [comment]
Hi @nimkar  This issue has been solved by accessing the Internet which has full permissions with out any restrictions and by enabling Vt-x in my Laptop.

Thank you for your support @nimkar
