### ISSUE TITLE
Issue regarding the oneops UI 

### ISSUE THREAD

**Issue by ksskSantosh** [oneops/setup#28]
Hi Team,
After we ran vagrant up command..
It had successfully installed....

 ==> default: Done with admin
  ==> default: OneOps should be up on http://localhost:3000
  ==> default: Configure your port forwarding and shut down iptables service (or configure it) if needed
  ==> default: All done at : 14:28:52

but UI did not show up at http://localhost:3000...
http://localhost:9090/users/sign_in

could you please help us..

**Comment by nimkar** [comment]
Hi @ksskSantosh is your issue resolved ? Vagrant actually maps the port to 9090 so you should be able to access the UI at http://localhost:9090.

**Comment by ksskSantosh** [comment]
Hi @nimkar , Yeah My previous issue #25 has been resolved. But now the UI is not up at http://localhost:9090. 

I am getting that some of the environments have not been setup as it is saying that there is no such directory over there...but the files are actually present over there.....I assumed that it was the problem for not showing the UI up... Is my Assumption wrong...???

==> default: env:
==> default: /etc/init.d/cassandra
==> default: : No such file or directory

Not only for cassandra but also for several like display, active mq,and so on.......

**Comment by ighouri** [comment]
@ksskSantosh 

What do you get when you hit http://localhost:9090 in your browser ?

Also, can you try restarting rails server and tails its output to see if restart solves the problem http://oneops.github.io/admin/testing/#ui-does-not-come-up
